apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: 'true'
    opsrc-provider: redhat
  name: ${REPO_NAME}-registry
spec:
  image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
  displayName: ${REPO_NAME}
  icon:
    base64data: ''
    mediatype: ''
  publisher: Red Hat
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
