---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    package-operator.run/phase: rbac
  name: route-monitor-operator-leader-election-rolebinding
  namespace: openshift-route-monitor-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-monitor-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: route-monitor-operator-system
    namespace: openshift-route-monitor-operator
