---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: route-monitor-operator
    component: operator
    control-plane: controller-manager
  name: route-monitor-operator-controller-manager
  namespace: openshift-route-monitor-operator
  annotations:
    package-operator.run/phase: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-monitor-operator
      component: operator
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: route-monitor-operator
        component: operator
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
              weight: 1
      containers:
        - args:
            - --zap-log-level=debug
            - --blackbox-image=$(BLACKBOX_IMAGE)
            - --blackbox-namespace=$(BLACKBOX_NAMESPACE)
            - --config=controller_manager_config.yaml
          command:
            - /manager
          env:
            - name: LOG_LEVEL
              value: "1"
            - name: BLACKBOX_IMAGE
              value: quay.io/prometheus/blackbox-exporter:master
            - name: BLACKBOX_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/app-sre/route-monitor-operator:v0.1.461-dbddf1f
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /controller_manager_config.yaml
              name: manager-config
              subPath: controller_manager_config.yaml
      securityContext:
        runAsNonRoot: true
      serviceAccountName: route-monitor-operator-system
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      volumes:
        - configMap:
            name: route-monitor-operator-manager-config
          name: manager-config
